# Generated by Django 5.0.1 on 2024-01-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='job',
            field=models.CharField(blank=True, choices=[('', 'What type of painting'), ('Interior', 'Interior'), ('Exterior', 'Exterior')], default='', max_length=20),
        ),
    ]
