# Generated by Django 5.0.1 on 2024-01-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_projects_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='user_phone',
            field=models.CharField(max_length=12),
        ),
    ]
